"""
Configuration package for C-SWIM + Economic Analysis

Provides utilities for data directory management and custom logging.
"""

from .settings import (
    APP_NAME,
    ROOT_DIR,
    DATA_DIR,
    ECON_DATA_DIR,
    DEFAULT_DATA_DIR,
    GROUND_GIC_DIR,
    FIGURES_DIR,
    LEAVE_OUT_SITES,
    P_TRAFO_BD,
    cut_off_volt,
    ALPHA_BETA_GIC_FILE,
    EFF_GIC_DIR,
    GND_GIC_DIR,
    ADMITTANCE_DIR,
    USE_ALPHA_BETA_SCENARIO,
    ALPHA_BETA_SCENARIOS,
    REGULAR_SCENARIOS,
    GDP_COLUMNS,
    EST_COLUMNS,
    DROP_COLUMNS,
    CSV_DTYPES,
    DEFAULT_THETA0,
    DEFAULT_TOLERANCE,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_BATCH_SIZE,
    DEFAULT_SAVE_BATCH_SIZE,
    PROCESS_GND_FILES,
    OUTPUT_FILES,
    IPOPT_EXEC,
    get_scenarios,
    get_simulation_config,
    get_data_dir,
    setup_logger,
)

__all__ = [
    "APP_NAME",
    "ROOT_DIR",
    "DATA_DIR",
    "ECON_DATA_DIR",
    "DEFAULT_DATA_DIR",
    "GROUND_GIC_DIR",
    "FIGURES_DIR",
    "LEAVE_OUT_SITES",
    "P_TRAFO_BD",
    "cut_off_volt",
    "ALPHA_BETA_GIC_FILE",
    "EFF_GIC_DIR",
    "GND_GIC_DIR",
    "ADMITTANCE_DIR",
    "USE_ALPHA_BETA_SCENARIO",
    "ALPHA_BETA_SCENARIOS",
    "REGULAR_SCENARIOS",
    "GDP_COLUMNS",
    "EST_COLUMNS",
    "DROP_COLUMNS",
    "CSV_DTYPES",
    "DEFAULT_THETA0",
    "DEFAULT_TOLERANCE",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_SAVE_BATCH_SIZE",
    "PROCESS_GND_FILES",
    "OUTPUT_FILES",
    "IPOPT_EXEC",
    "get_scenarios",
    "get_simulation_config",
    "get_data_dir",
    "setup_logger",
]
